# Generated by Django 3.1.7 on 2021-05-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthymind', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_owner',
        ),
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Blog_owner', to='healthymind.user'),
            preserve_default=False,
        ),
    ]
