# Generated by Django 3.1.7 on 2021-05-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthymind', '0004_auto_20210529_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeblog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
