# Generated by Django 3.1.7 on 2021-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthymind', '0005_storeblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeblog',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
